name: 'DEBUG'

on:
  workflow_dispatch:
    inputs:
      targetOrgUser:
        description: 'Target Scratch-Org-User. Example: "test-st7lwi7yzzqk@example.com"'
        required: true
jobs:
  Push-Scratch-Org:
    runs-on: ubuntu-latest
    container: salesforce/salesforcedx:latest-full
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download auth-file for org
        uses: fs24-chrter/test-workflow-download@master
        with:
          workflow: upload.yml
          name: 7efd4881-8077-4956-a3c8-6ef4898c3863
          search_artifacts: true
      - name: Print files
        run: ls -R