name: Upload

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          mkdir artifact
          echo $GITHUB_SHA > artifact/sha
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact
  upload-multiple:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          mkdir artifact1 artifact2
          echo $GITHUB_SHA > artifact1/sha1
          echo $GITHUB_SHA > artifact2/sha2
      - name: Upload first
        uses: actions/upload-artifact@v2
        with:
          name: d1f10237-4b14-40fb-817c-3a0010b8366e
          path: artifact1
      - name: Upload second
        uses: actions/upload-artifact@v2
        with:
          name: 7efd4881-8077-4956-a3c8-6ef4898c3863
          path: artifact2
